Panchani0925/EduNex-CS-147-

EduNex-app/.gitignore
EduNex-app/README.md
EduNex-app/eslint.config.js
EduNex-app/index.html
EduNex-app/package-lock.json
EduNex-app/package.json
EduNex-app/postcss.config.js
EduNex-app/src/App.css
EduNex-app/src/App.jsx
EduNex-app/src/frontend/pages/Home.jsx
EduNex-app/src/index.css
EduNex-app/src/main.jsx
EduNex-app/tailwind.config.js
EduNex-app/vite.config.js

Establish a new project configuration using Vite, integrating React and Tailwind CSS for styling. This setup includes essential files and configurations for development, linting, and routing.

Setup Vite with React and Tailwind CSS

---

routes.js

initialize express and install dependencies

chore: initialize express and install dependencies

---

routes.js

feat: add user registration route

---

routes.js

database query to check if user exits

feat: add database query to check if user exists

---

routes.js

query to insert user into database

feat: add query to insert user into database

---

routes.js

feat: add user login route

---

routes.js

feat: add reset password route

---

routes.js

feat: add again  reset password route

---

routes.js

feat: add student dashboard route

---

routes.js

add query to fetch enrolled courses for student dashboard

feat: add query to fetch enrolled courses for student dashboard

---

routes.js

add query to fetch performance analytics for student dashboard

feat: add query to fetch performance analytics for student dashboard

---

routes.js

feat: add teacher dashboard route

---

routes.js

add query to fetch courses for teacher dashboard

feat: add query to fetch courses for teacher dashboard

---

routes.js

add  students performance data

feat: add  students performance data

---

routes.js

feat: add parent  dashboard route

---

routes.js

add no students are linked, return an empty progress array

feat: add no students are linked, return an empty progress array

---

routes.js

add fetch progress for each student

feat: add fetch progress for each student

---

routes.js

feat: add fetch course details

---

routes.js

add fetch course modules and course resources

feat: add fetch course modules and course resources

---

routes.js

add assignment submission route for students

feat: add assignment submission route for students

---

routes.js

add students performance analytics page

feat: add students performance analytics page

---

routes.js

add Communication and notification system

feat: add Communication and notification system

---

routes.js

feat: add Live classes page

---

routes.js

add notifications and alerts page

feat: add notifications and alerts page

---

routes.js

add parents dashboard enhancement

feat: add parents dashboard enhancement

---

routes.js

add Student Wellbeing & Assistance Tools

feat: add Student Wellbeing & Assistance Tools

---

routes.js

feat: add Admin Dashborad

---

routes.js

feat: add Delete User (Admin Only)

---

MyApp/app/teacher/make-class.tsx

add Teacher class with properties and methods

feat: add Teacher class with properties and methods

---

MyApp/app/teacher/make-class.tsx

Initial project setup with SafeAreaView and StatusBar

Initial project setup with SafeAreaView and StatusBar

---

MyApp/app/teacher/make-class.tsx

Add KeyboardAvoidingView and ScrollView for better UX

Add KeyboardAvoidingView and ScrollView for better UX

---

MyApp/app/teacher/make-class.tsx

Implement header with curved design and title text

Implement header with curved design and title text

---

package-lock.json
package.json

Add speakeasy package for Two-Factor Authentication (2FA)

Add speakeasy package for Two-Factor Authentication (2FA)

---

routes.js

Fetch all users and students

---

routes.js

Add a new student

---

routes.js

// Add new resource (Only Links)

// Add new resource (Only Links)

---

routes.js

// Get the total number of subjects (courses)

// Get the total number of subjects (courses)

---

routes.js

// User Login Route

---

backend node/index.js

Add endpoint to fetch assignments for a specific course.

Add endpoint to fetch assignments for a specific course.

---

backend node/index.js

Add endpoint to create a new assignment.

Add endpoint to create a new assignment.

---

backend node/index.js

Add endpoint to fetch resources for a specific course.

Add endpoint to fetch resources for a specific course.

---

backend node/index.js

Fetch all courses with their live class schedules

Fetch all courses with their live class schedules

---

backend node/index.js

Fetch notifications (Live Classes and Feedback)

Fetch notifications (Live Classes and Feedback)

---

backend node/index.js

Add endpoints to fetch study resources and scheduled live classes.

Add endpoints to fetch study resources and scheduled live classes.

---

backend node/index.js

Fetch students with low scores

Fetch students with low scores

---

backend node/index.js

Fetch all teachers dynamically

Fetch all teachers dynamically

---

backend node/index.js

Get the total number of students

Get the total number of students

---

backend node/index.js

Get the total number of teachers

Get the total number of teachers

---

backend node/index.js

Get the total number of subjects (courses)

Get the total number of subjects (courses)

---

backend node/index.js

Fetch All Available Courses

---

backend node/index.js

Endpoint to handle form submissions

Endpoint to handle form submissions

---

backend node/index.js

Fetch all contact messages

---

backend node/index.js

User Login Route

---

backend node/index.js

Start Server
